window.questions = [
  // --- LEVEL 1: Basics (1-100) ---
  { "id": 1, "grammar": "L1: Be verb", "jp": "私は新しいプロジェクトマネージャーです。", "en": "I am the new project manager", "display": "I am / the new / project manager", "point": "I am ...は自己紹介の基本形です。" },
  { "id": 2, "grammar": "L1: Present Simple", "jp": "私はIT企業で働いています。", "en": "I work for an IT company", "display": "I work / for an IT company", "point": "所属は work for を使います。" },
  { "id": 3, "grammar": "L1: Present Continuous", "jp": "彼は今、電話に出ています。", "en": "He is on the phone now", "display": "He is / on the phone / now", "point": "is on the phone で電話中です。" },
  { "id": 4, "grammar": "L1: Past Simple", "jp": "昨日、見積もりを送りました。", "en": "I sent the estimate yesterday", "display": "I sent / the estimate / yesterday", "point": "sendの過去形は不規則変化の sent です。" },
  { "id": 5, "grammar": "L1: Can", "jp": "明日お会いできますか？", "en": "Can I meet you tomorrow", "display": "Can I / meet you / tomorrow", "point": "許可や可能性を問う can です。" },
  { "id": 6, "grammar": "L1: Be verb", "jp": "田中さんは今、会議室にいます。", "en": "Mr. Tanaka is in the meeting room now", "display": "Mr. Tanaka / is / in the meeting room / now", "point": "場所を表す時は is in ... を使います。" },
  { "id": 7, "grammar": "L1: Be verb", "jp": "彼らは私たちのクライアントです。", "en": "They are our clients", "display": "They are / our clients", "point": "複数形 They に合わせて are になります。" },
  { "id": 8, "grammar": "L1: Be verb (Neg)", "jp": "このファイルは重要ではありません。", "en": "This file is not important", "display": "This file / is not / important", "point": "be 動詞の後に not を置くと否定文になります。" },
  { "id": 9, "grammar": "L1: Be verb (Quest)", "jp": "あなたは営業部の所属ですか？", "en": "Are you in the sales department", "display": "Are you / in the sales department", "point": "be 動詞を文頭に出すと疑問文になります。" },
  { "id": 10, "grammar": "L1: Present Simple", "jp": "彼女は英語を上手に話します。", "en": "She speaks English well", "display": "She speaks / English / well", "point": "主語が She の時は動詞に s が付きます。" },
  { "id": 11, "grammar": "L1: Present Simple (Neg)", "jp": "私はコーヒーを飲みません。", "en": "I do not drink coffee", "display": "I do not / drink coffee", "point": "一般動詞の否定は do not を使います。" },
  { "id": 12, "grammar": "L1: Present Simple (Neg)", "jp": "彼は名刺を持っていません。", "en": "He does not have a business card", "display": "He / does not have / a business card", "point": "三人称単数の否定は does not を使います。" },
  { "id": 13, "grammar": "L1: Wh-Quest", "jp": "あなたは何時にオフィスに来ますか？", "en": "What time do you come to the office", "display": "What time / do you come / to the office", "point": "具体的な時間は What time ...? で聞きます。" },
  { "id": 14, "grammar": "L1: Imperative", "jp": "ここに署名をお願いします。", "en": "Please sign here", "display": "Please / sign / here", "point": "動詞の原形で始めると命令文（依頼）になります。" },
  { "id": 15, "grammar": "L1: Imperative (Neg)", "jp": "この部屋で電話をしないでください。", "en": "Please do not use the phone in this room", "display": "Please / do not use / the phone / in this room", "point": "Do not + 動詞の原形で「〜しないで」となります。" },
  { "id": 16, "grammar": "L1: Can", "jp": "私を手伝ってくれますか？", "en": "Can you help me", "display": "Can you / help me", "point": "Can you ...? は依頼の表現です。" },
  { "id": 17, "grammar": "L1: Can", "jp": "ここで待ってもいいですか？", "en": "Can I wait here", "display": "Can I / wait / here", "point": "Can I ...? は許可を求める表現です。" },
  { "id": 18, "grammar": "L1: Present Continuous", "jp": "私は今、メールを書いています。", "en": "I am writing an email now", "display": "I am writing / an email / now", "point": "be 動詞 + ing で進行形になります。" },
  { "id": 19, "grammar": "L1: Present Continuous (Quest)", "jp": "あなたは今、何を作っていますか？", "en": "What are you making now", "display": "What / are you making / now", "point": "疑問詞 + be動詞 + 主語 + ing の語順です。" },
  { "id": 20, "grammar": "L1: Wh-Quest", "jp": "誰がこのプロジェクトの担当ですか？", "en": "Who is in charge of this project", "display": "Who / is in charge of / this project", "point": "be in charge of で「担当している」です。" },
  { "id": 21, "grammar": "L1: Past Simple (Be)", "jp": "昨日は休みでした。", "en": "I was off yesterday", "display": "I was / off / yesterday", "point": "I の過去の be 動詞は was です。" },
  { "id": 22, "grammar": "L1: Past Simple (Reg)", "jp": "私は昨日、その資料をチェックしました。", "en": "I checked the document yesterday", "display": "I checked / the document / yesterday", "point": "規則動詞は ed を付けて過去を表します。" },
  { "id": 23, "grammar": "L1: Past Simple (Irreg)", "jp": "私は今朝、メールを送りました。", "en": "I sent an email this morning", "display": "I sent / an email / this morning", "point": "send の過去形は sent です。" },
  { "id": 24, "grammar": "L1: There is", "jp": "机の上に資料があります。", "en": "There is a document on the desk", "display": "There is / a document / on the desk", "point": "単数の存在は There is を使います。" },
  { "id": 25, "grammar": "L1: There are", "jp": "このビルには3つの会議室があります。", "en": "There are three meeting rooms in this building", "display": "There are / three meeting rooms / in this building", "point": "複数の存在は There are を使います。" },
  { "id": 26, "grammar": "L1: Pronouns", "jp": "これは私の名刺です。", "en": "This is my business card", "display": "This is / my business card", "point": "my は「私の」という所有格です。" },
  { "id": 27, "grammar": "L1: Wh-Quest", "jp": "このペンは誰のものですか？", "en": "Whose pen is this", "display": "Whose pen / is this", "point": "Whose で所有者を尋ねます。" },
  { "id": 28, "grammar": "L1: Frequency", "jp": "私はいつも7時に起きます。", "en": "I always get up at seven", "display": "I always / get up / at seven", "point": "always は動詞の前に置きます。" },
  { "id": 29, "grammar": "L1: Prepositions", "jp": "月曜日に会いましょう。", "en": "Let's meet on Monday", "display": "Let's meet / on Monday", "point": "曜日の前には on を使います。" },
  { "id": 30, "grammar": "L1: Wh-Quest", "jp": "この単語はどういう意味ですか？", "en": "What does this word mean", "display": "What / does this word / mean", "point": "mean は「意味する」という動詞です。" },
  { "id": 31, "grammar": "L1: Pronouns", "jp": "彼にメールを送ってください。", "en": "Please send him an email", "display": "Please / send him / an email", "point": "「彼に」は目的格の him です。" },
  { "id": 32, "grammar": "L1: Whose", "jp": "これは誰のパソコンですか？", "en": "Whose computer is this", "display": "Whose computer / is this", "point": "Whose + 名詞 で「誰の〜」です。" },
  { "id": 33, "grammar": "L1: Prepositions", "jp": "会議は3時に終わります。", "en": "The meeting ends at three", "display": "The meeting / ends / at three", "point": "時刻の前には at を使います。" },
  { "id": 34, "grammar": "L1: Past Simple (Quest)", "jp": "そのニュースを聞きましたか？", "en": "Did you hear the news", "display": "Did you / hear / the news", "point": "過去の疑問文は Did を使います。" },
  { "id": 35, "grammar": "L1: Past Simple (Neg)", "jp": "私はその報告書を読みませんでした。", "en": "I did not read the report", "display": "I / did not read / the report", "point": "否定は did not + 動詞の原形です。" },
  { "id": 36, "grammar": "L1: Wh-Quest", "jp": "誰がその会議に出席しましたか？", "en": "Who attended the meeting", "display": "Who / attended / the meeting", "point": "Whoが主語ならそのまま動詞を過去形にします。" },
  { "id": 37, "grammar": "L1: Wh-Quest", "jp": "いつ彼に会いましたか？", "en": "When did you meet him", "display": "When / did you meet / him", "point": "When did you ...? で時を尋ねます。" },
  { "id": 38, "grammar": "L1: Wh-Quest", "jp": "どこで名刺をもらいましたか？", "en": "Where did you get the business card", "display": "Where / did you get / the business card", "point": "Where did you ...? で場所を尋ねます。" },
  { "id": 39, "grammar": "L1: There is (Quest)", "jp": "ロビーに誰かいますか？", "en": "Is there anyone in the lobby", "display": "Is there anyone / in the lobby", "point": "疑問文では anyone を使います。" },
  { "id": 40, "grammar": "L1: May I", "jp": "質問してもよろしいですか？", "en": "May I ask a question", "display": "May I / ask / a question", "point": "May I ...? は丁寧な許可の表現です。" },
  { "id": 41, "grammar": "L1: Present Simple", "jp": "私たちの会社は良い製品を売っています。", "en": "Our company sells good products", "display": "Our company / sells / good products", "point": "三人称単数の s を忘れないようにしましょう。" },
  { "id": 42, "grammar": "L1: Why", "jp": "なぜあなたはここにいるのですか？", "en": "Why are you here", "display": "Why / are you / here", "point": "Why で理由を尋ねます。" },
  { "id": 43, "grammar": "L1: How many", "jp": "参加者は何人ですか？", "en": "How many participants are there", "display": "How many participants / are there", "point": "数を数えるときは How many + 複数形です。" },
  { "id": 44, "grammar": "L1: Adverbs", "jp": "彼はいつも一生懸命働きます。", "en": "He always works hard", "display": "He always / works hard", "point": "hard は「一生懸命に」という副詞です。" },
  { "id": 45, "grammar": "L1: Past Simple", "jp": "私たちは新しい車を買いました。", "en": "We bought a new car", "display": "We bought / a new car", "point": "buy の過去形は bought です。" },
  { "id": 46, "grammar": "L1: Past Simple", "jp": "彼女はそのファイルを見つけました。", "en": "She found the file", "display": "She found / the file", "point": "find の過去形は found です。" },
  { "id": 47, "grammar": "L1: Past Simple", "jp": "私たちは新しいオフィスへ行きました。", "en": "We went to the new office", "display": "We went / to the new office", "point": "go の過去形は went です。" },
  { "id": 48, "grammar": "L1: How much", "jp": "これはいくらですか？", "en": "How much is this", "display": "How much / is this", "point": "値段を尋ねる基本表現です。" },
  { "id": 49, "grammar": "L1: Can", "jp": "あなたはその問題を解決できますか？", "en": "Can you solve the problem", "display": "Can you / solve / the problem", "point": "solve は「解決する」という動詞です。" },
  { "id": 50, "grammar": "L1: Be verb", "jp": "その価格は非常に妥当です。", "en": "The price is very reasonable", "display": "The price / is / very reasonable", "point": "reasonable は「手頃な・妥当な」です。" },
  { "id": 51, "grammar": "L1: Present Simple", "jp": "私は毎日たくさんのメールを受け取ります。", "en": "I receive many emails every day", "display": "I receive / many emails / every day", "point": "receive は「受け取る」という動詞です。" },
  { "id": 52, "grammar": "L1: Wh-Quest", "jp": "あなたの役職は何ですか？", "en": "What is your job title", "display": "What / is / your job title", "point": "job title で「役職名」です。" },
  { "id": 53, "grammar": "L1: Wh-Quest", "jp": "本社はどこにありますか？", "en": "Where is the head office", "display": "Where is / the head office", "point": "head office で「本社」です。" },
  { "id": 54, "grammar": "L1: Past Simple", "jp": "彼は昨日、重要な決定をしました。", "en": "He made an important decision yesterday", "display": "He made / an important decision / yesterday", "point": "make a decision で「決定する」です。" },
  { "id": 55, "grammar": "L1: Past Simple", "jp": "私たちは昨年、大きな契約を獲得しました。", "en": "We got a big contract last year", "display": "We got / a big contract / last year", "point": "contract は「契約」です。" },
  { "id": 56, "grammar": "L1: Can", "jp": "あなたのペンを借りてもいいですか？", "en": "Can I borrow your pen", "display": "Can I / borrow / your pen", "point": "borrow は「借りる」です。" },
  { "id": 57, "grammar": "L1: Prepositions", "jp": "部長は今、会議室にいます。", "en": "The manager is in the meeting room now", "display": "The manager / is in / the meeting room / now", "point": "空間の中にいるときは in です。" },
  { "id": 58, "grammar": "L1: Ago", "jp": "彼は5分前に出発しました。", "en": "He left five minutes ago", "display": "He left / five minutes ago", "point": "ago は「〜前」を表します。" },
  { "id": 59, "grammar": "L1: Next", "jp": "来週お会いしましょう。", "en": "Let's meet next week", "display": "Let's meet / next week", "point": "next week の前には前置詞は不要です。" },
  { "id": 60, "grammar": "L1: Present Continuous", "jp": "私たちは新製品をテストしています。", "en": "We are testing a new product", "display": "We are testing / a new product", "point": "進行形の基本です。" },
  { "id": 61, "grammar": "L1: Imperative", "jp": "タクシーで行きましょう。", "en": "Let's go by taxi", "display": "Let's go / by taxi", "point": "by + 交通手段 で表します。" },
  { "id": 62, "grammar": "L1: Be verb", "jp": "私は元気です、ありがとう。", "en": "I am fine, thank you", "display": "I am fine, / thank you", "point": "挨拶への返しです。" },
  { "id": 63, "grammar": "L1: Present Simple", "jp": "彼は人事部で働いています。", "en": "He works in the HR department", "display": "He works / in the HR department", "point": "部署の前には in を使います。" },
  { "id": 64, "grammar": "L1: Wh-Quest", "jp": "オフィスはどこですか？", "en": "Where is your office", "display": "Where is / your office", "point": "場所を尋ねます。" },
  { "id": 65, "grammar": "L1: Wh-Quest", "jp": "誰がこのペンの持ち主ですか？", "en": "Who owns this pen", "display": "Who / owns / this pen", "point": "own は「所有する」という動詞です。" },
  { "id": 66, "grammar": "L1: Prepositions", "jp": "私の席は窓の近くです。", "en": "My desk is near the window", "display": "My desk / is near / the window", "point": "near は「〜の近くに」です。" },
  { "id": 67, "grammar": "L1: Time", "jp": "始業時間は9時です。", "en": "The work starts at 9 AM", "display": "The work / starts / at 9 AM", "point": "始まりを表す starts です。" },
  { "id": 68, "grammar": "L1: Numbers", "jp": "20名分のランチを予約してください。", "en": "Please book lunch for twenty people", "display": "Please book / lunch / for twenty people", "point": "book は「予約する」という動詞です。" },
  { "id": 69, "grammar": "L1: Adjectives", "jp": "その価格は妥当です。", "en": "The price is reasonable", "display": "The price / is / reasonable", "point": "reasonable はビジネスでよく使われます。" },
  { "id": 70, "grammar": "L1: Wh-Quest", "jp": "なぜ計画が変更されたのですか？", "en": "Why was the plan changed", "display": "Why was / the plan / changed", "point": "Why で理由を聞きます。" },
  { "id": 71, "grammar": "L1: Wh-Quest", "jp": "どちらの選択肢が良いですか？", "en": "Which option is better", "display": "Which option / is / better", "point": "Which で選択肢を聞きます。" },
  { "id": 72, "grammar": "L1: Be verb", "jp": "彼は今日はオフィスにいません。", "en": "He is not in the office today", "display": "He is not / in the office / today", "point": "不在を表す not in the office です。" },
  { "id": 73, "grammar": "L1: Can", "jp": "このファイルを開けますか？", "en": "Can you open this file", "display": "Can you / open / this file", "point": "能力や依頼の can です。" },
  { "id": 74, "grammar": "L1: Present Simple", "jp": "社長は毎朝コーヒーを飲みます。", "en": "The president drinks coffee every morning", "display": "The president / drinks coffee / every morning", "point": "習慣を表す現在形です。" },
  { "id": 75, "grammar": "L1: Past Simple", "jp": "今朝、彼と話しました。", "en": "I talked with him this morning", "display": "I talked / with him / this morning", "point": "talked with で「〜と話した」です。" },
  { "id": 76, "grammar": "L1: Wh-Quest", "jp": "お手洗いはどこですか？", "en": "Where is the restroom", "display": "Where is / the restroom", "point": "場所を聞く基本表現です。" },
  { "id": 77, "grammar": "L1: Wh-Quest", "jp": "何名の参加者が来ますか？", "en": "How many participants are coming", "display": "How many participants / are coming", "point": "進行形で予定を表すこともあります。" },
  { "id": 78, "grammar": "L1: Wh-Quest", "jp": "このペンは誰のものですか？", "en": "Whose pen is this", "display": "Whose pen / is this", "point": "所有者を尋ねます。" },
  { "id": 79, "grammar": "L1: Past Simple", "jp": "今朝、新しい情報を得ました。", "en": "I got some new information this morning", "display": "I got / some new information / this morning", "point": "get の過去形 got です。" },
  { "id": 80, "grammar": "L1: Past Simple", "jp": "私は昨日、そのシステムを使いました。", "en": "I used the system yesterday", "display": "I used / the system / yesterday", "point": "規則動詞の過去形です。" },
  { "id": 81, "grammar": "L1: Imperative", "jp": "もう一度言ってください。", "en": "Please say that again", "display": "Please / say / that again", "point": "聞き取れない時の基本フレーズです。" },
  { "id": 82, "grammar": "L1: Imperative", "jp": "私に資料を見せてください。", "en": "Please show me the document", "display": "Please show me / the document", "point": "show 人 物 の語順です。" },
  { "id": 83, "grammar": "L1: Imperative", "jp": "ここでタバコを吸わないでください。", "en": "Please do not smoke here", "display": "Please / do not smoke / here", "point": "禁止の依頼です。" },
  { "id": 84, "grammar": "L1: Can", "jp": "この書類をスキャンしてくれますか？", "en": "Can you scan this document", "display": "Can you / scan / this document", "point": "依頼の can です。" },
  { "id": 85, "grammar": "L1: Wh-Quest", "jp": "これは誰のスマートフォンですか？", "en": "Whose smartphone is this", "display": "Whose smartphone / is this", "point": "Whose で所有を聞きます。" },
  { "id": 86, "grammar": "L1: Prepositions", "jp": "駅で会いましょう。", "en": "Let's meet at the station", "display": "Let's meet / at the station", "point": "特定の場所は at です。" },
  { "id": 87, "grammar": "L1: Wh-Quest", "jp": "どのような会社ですか？", "en": "What kind of company is it", "display": "What kind of / company / is it", "keywords": ["What kind of"], "point": "種類を尋ねます。" },
  { "id": 88, "grammar": "L1: Present Continuous", "jp": "彼らは今、議論をしていません。", "en": "They are not having a discussion now", "display": "They are not / having a discussion / now", "point": "進行形の否定です。" },
  { "id": 89, "grammar": "L1: Past Simple", "jp": "彼は私にその本をくれました。", "en": "He gave me the book", "display": "He gave / me / the book", "point": "give の過去形 gave です。" },
  { "id": 90, "grammar": "L1: Present Simple", "jp": "私は週末に働きます。", "en": "I work on weekends", "display": "I work / on weekends", "point": "習慣的な仕事は現在形です。" },
  { "id": 91, "grammar": "L1: Wh-Quest", "jp": "昨日のランチに何を食べましたか？", "en": "What did you eat for lunch yesterday", "display": "What / did you eat / for lunch / yesterday", "point": "What did you ...? の形です。" },
  { "id": 92, "grammar": "L1: Prepositions", "jp": "同僚と一緒にランチに行きました。", "en": "I went to lunch with my colleagues", "display": "I went to lunch / with / my colleagues", "point": "「〜と一緒に」は with です。" },
  { "id": 93, "grammar": "L1: Adverbs", "jp": "彼はとても速く走ります。", "en": "He runs very fast", "display": "He runs / very fast", "point": "fast は副詞でもあります。" },
  { "id": 94, "grammar": "L1: Wh-Quest", "jp": "あなたは名刺を何枚持っていますか？", "en": "How many business cards do you have", "display": "How many business cards / do you have", "point": "How many + 複数名詞 です。" },
  { "id": 95, "grammar": "L1: Past Simple", "jp": "私は今朝、鍵をなくしました。", "en": "I lost my key this morning", "display": "I lost / my key / this morning", "point": "lose の過去形 lost です。" },
  { "id": 96, "grammar": "L1: Present Simple", "jp": "彼はいつも親切です。", "en": "He is always kind", "display": "He is / always / kind", "point": "頻度の副詞の位置に注目です。" },
  { "id": 97, "grammar": "L1: Plural", "jp": "これらの資料は古いですよ。", "en": "These documents are old", "display": "These documents / are / old", "point": "this の複数は these です。" },
  { "id": 98, "grammar": "L1: Be verb", "jp": "今日はとても良い天気です。", "en": "It is very sunny today", "display": "It is / very sunny / today", "point": "天候の主語は it です。" },
  { "id": 99, "grammar": "L1: Wh-Quest", "jp": "調子はどうですか？", "en": "How are you doing", "display": "How / are you / doing", "point": "挨拶の定番です。" },
  { "id": 100, "grammar": "L1: Present Simple", "jp": "月曜日はいつも忙しいです。", "en": "I am always busy on Mondays", "display": "I am always / busy / on Mondays", "point": "習慣的な曜日は複数形にします。" }
];
