window.questions = [
  { "id": 1, "grammar": "L1: Be verb", "jp": "私は新しいプロジェクトマネージャーです。", "en": "I am the new project manager", "display": "I am / the new / project manager", "point": "自己紹介の基本形です。", "alt": "My name is Tanaka, and I am the manager." },
  { "id": 2, "grammar": "L1: Present Simple", "jp": "私はIT企業で働いています。", "en": "I work for an IT company", "display": "I work / for / an IT company", "point": "所属は work for を使います。", "alt": "I am with an IT firm." },
  { "id": 3, "grammar": "L1: Present Continuous", "jp": "彼は今、電話に出ています。", "en": "He is on the phone now", "display": "He is / on the phone / now", "point": "is on the phone で電話中です。", "alt": "He is currently on another line." },
  { "id": 4, "grammar": "L1: Past Simple", "jp": "昨日、見積もりを送りました。", "en": "I sent the estimate yesterday", "display": "I sent / the estimate / yesterday", "point": "sendの過去形は不規則変化の sent です。", "alt": "The quote was sent yesterday." },
  { "id": 5, "grammar": "L1: Can", "jp": "明日お会いできますか？", "en": "Can I meet you tomorrow", "display": "Can I / meet you / tomorrow", "point": "許可や可能性を問う can です。", "alt": "Would it be possible to meet tomorrow?" },
  { "id": 6, "grammar": "L1: Be verb", "jp": "田中さんは今、会議室にいます。", "en": "Mr. Tanaka is in the meeting room now", "display": "Mr. Tanaka / is in / the meeting room / now", "point": "場所を表す時は is in ... を使います。", "alt": "He is in a meeting at the moment." },
  { "id": 7, "grammar": "L1: Be verb", "jp": "彼らは私たちのクライアントです。", "en": "They are our clients", "display": "They are / our clients", "point": "複数形 They に合わせて are になります。", "alt": "Those people are our customers." },
  { "id": 8, "grammar": "L1: Be verb (Neg)", "jp": "このファイルは重要ではありません。", "en": "This file is not important", "display": "This file / is not / important", "point": "be 動詞の後に not を置くと否定文になります。", "alt": "This document is not necessary." },
  { "id": 9, "grammar": "L1: Be verb (Quest)", "jp": "あなたは営業部の所属ですか？", "en": "Are you in the sales department", "display": "Are you / in the sales department", "point": "be 動詞を文頭に出すと疑問文になります。", "alt": "Do you work for the sales team?" },
  { "id": 10, "grammar": "L1: Present Simple", "jp": "彼女は英語を上手に話します。", "en": "She speaks English well", "display": "She / speaks English / well", "point": "主語が She の時は動詞に s が付きます。", "alt": "Her English is very good." },
  { "id": 11, "grammar": "L1: Wh-Quest", "jp": "あなたは何時にオフィスに来ますか？", "en": "What time do you come to the office", "display": "What time / do you come / to the office", "point": "具体的な時間は What time ...? で聞きます。", "alt": "When do you arrive at work?" },
  { "id": 12, "grammar": "L1: Imperative", "jp": "ここに署名をお願いします。", "en": "Please sign here", "display": "Please / sign / here", "point": "動詞の原形で始めると依頼になります。", "alt": "Could you put your signature here?" },
  { "id": 13, "grammar": "L1: Can", "jp": "私を手伝ってくれますか？", "en": "Can you help me", "display": "Can you / help me", "point": "Can you ...? は依頼の表現です。", "alt": "Could you give me a hand?" },
  { "id": 14, "grammar": "L1: Present Continuous", "jp": "私は今、メールを書いています。", "en": "I am writing an email now", "display": "I am writing / an email / now", "point": "be 動詞 + ing で進行形になります。", "alt": "I'm currently replying to an email." },
  { "id": 15, "grammar": "L1: Wh-Quest", "jp": "誰がこのプロジェクトの担当ですか？", "en": "Who is in charge of this project", "display": "Who / is in charge of / this project", "point": "be in charge of で「担当している」です。", "alt": "Who is leading this project?" },
  { "id": 16, "grammar": "L1: Past Simple", "jp": "私は昨日、その資料をチェックしました。", "en": "I checked the document yesterday", "display": "I checked / the document / yesterday", "point": "規則動詞は ed を付けます。", "alt": "I looked over the files yesterday." },
  { "id": 17, "grammar": "L1: There is", "jp": "机の上に資料があります。", "en": "There is a document on the desk", "display": "There is / a document / on the desk", "point": "単数の存在は There is です。", "alt": "A document is on the desk." },
  { "id": 18, "grammar": "L1: Wh-Quest", "jp": "このペンは誰のものですか？", "en": "Whose pen is this", "display": "Whose pen / is this", "point": "Whose で所有者を尋ねます。", "alt": "Does this pen belong to anyone?" },
  { "id": 19, "grammar": "L1: Frequency", "jp": "私はいつも7時に起きます。", "en": "I always get up at seven", "display": "I always / get up / at seven", "point": "always は動詞の前に置きます。", "alt": "I wake up at seven every morning." },
  { "id": 20, "grammar": "L1: Prepositions", "jp": "月曜日に会いましょう。", "en": "Let's meet on Monday", "display": "Let's meet / on Monday", "point": "曜日の前には on を使います。", "alt": "We shall meet this Monday." },
  { "id": 21, "grammar": "L1: Wh-Quest", "jp": "誰がその会議に出席しましたか？", "en": "Who attended the meeting", "display": "Who / attended / the meeting", "point": "Whoが主語ならそのまま動詞を過去形にします。", "alt": "Who was present?" },
  { "id": 22, "grammar": "L1: Wh-Quest", "jp": "どこで名刺をもらいましたか？", "en": "Where did you get the business card", "display": "Where / did you get / the business card", "point": "Where did you ...? で場所を尋ねます。", "alt": "Where did you receive that card?" },
  { "id": 23, "grammar": "L1: May I", "jp": "質問してもよろしいですか？", "en": "May I ask a question", "display": "May I / ask / a question", "point": "May I ...? は丁寧な許可の表現です。", "alt": "Could I ask a quick question?" },
  { "id": 24, "grammar": "L1: Present Simple", "jp": "私たちの会社は良い製品を売っています。", "en": "Our company sells good products", "display": "Our company / sells / good products", "point": "三人称単数の s を忘れないようにしましょう。", "alt": "We offer high-quality items." },
  { "id": 25, "grammar": "L1: How many", "jp": "参加者は何人ですか？", "en": "How many participants are there", "display": "How many participants / are there", "point": "数を数えるときは How many です。", "alt": "What is the total number of attendees?" },
  { "id": 26, "grammar": "L1: Past Simple", "jp": "私たちは新しいオフィスへ行きました。", "en": "We went to the new office", "display": "We went / to the new office", "point": "go の過去形は went です。", "alt": "We visited the new office space." },
  { "id": 27, "grammar": "L1: Can", "jp": "あなたはその問題を解決できますか？", "en": "Can you solve the problem", "display": "Can you / solve / the problem", "point": "solve は「解決する」です。", "alt": "Are you able to handle this issue?" },
  { "id": 28, "grammar": "L1: Be verb", "jp": "本社はどこにありますか？", "en": "Where is the head office", "display": "Where is / the head office", "point": "head office で「本社」です。", "alt": "Where is your company located?" },
  { "id": 29, "grammar": "L1: Can", "jp": "あなたのペンを借りてもいいですか？", "en": "Can I borrow your pen", "display": "Can I / borrow / your pen", "point": "borrow は「借りる」です。", "alt": "May I use your pen?" },
  { "id": 30, "grammar": "L1: Next", "jp": "来週お会いしましょう。", "en": "Let's meet next week", "display": "Let's meet / next week", "point": "next week の前には前置詞は不要です。", "alt": "I look forward to next week." },
  { "id": 31, "grammar": "L1: Imperative", "jp": "タクシーで行きましょう。", "en": "Let's go by taxi", "display": "Let's go / by taxi", "point": "by + 交通手段 で表します。", "alt": "Shall we take a cab?" },
  { "id": 32, "grammar": "L1: Wh-Quest", "jp": "オフィスはどこですか？", "en": "Where is your office", "display": "Where is / your office", "point": "場所を尋ねます。", "alt": "Could you tell me your location?" },
  { "id": 33, "grammar": "L1: Numbers", "jp": "20名分のランチを予約してください。", "en": "Please book lunch for twenty people", "display": "Please book / lunch / for / twenty people", "point": "book は「予約する」です。", "alt": "I need a table for twenty." },
  { "id": 34, "grammar": "L1: Wh-Quest", "jp": "どちらの選択肢が良いですか？", "en": "Which option is better", "display": "Which option / is / better", "point": "Which で選択肢を聞きます。", "alt": "Which one do you prefer?" },
  { "id": 35, "grammar": "L1: Can", "jp": "このファイルを開けますか？", "en": "Can you open this file", "display": "Can you / open / this file", "point": "依頼の can です。", "alt": "Could you please open this?" },
  { "id": 36, "grammar": "L1: Wh-Quest", "jp": "お手洗いはどこですか？", "en": "Where is the restroom", "display": "Where is / the restroom", "point": "場所を聞く基本表現です。", "alt": "Where can I find the toilet?" },
  { "id": 37, "grammar": "L1: Past Simple", "jp": "今朝、新しい情報を得ました。", "en": "I got some new information this morning", "display": "I got / some new information / this morning", "point": "get の過去形 got です。", "alt": "I received an update earlier." },
  { "id": 38, "grammar": "L1: Imperative", "jp": "私に資料を見せてください。", "en": "Please show me the document", "display": "Please / show me / the document", "point": "show 人 物 の語順です。", "alt": "May I see the files?" },
  { "id": 39, "grammar": "L1: Wh-Quest", "jp": "これは誰のスマートフォンですか？", "en": "Whose smartphone is this", "display": "Whose smartphone / is this", "point": "Whose で所有を聞きます。", "alt": "Who does this belong to?" },
  { "id": 40, "grammar": "L1: Wh-Quest", "jp": "調子はどうですか？", "en": "How are you doing", "display": "How / are you / doing", "point": "挨拶の定番です。", "alt": "How is everything?" },
  { "id": 41, "grammar": "L1: Past Simple", "jp": "彼にメールを送りました。", "en": "I sent him an email", "display": "I sent / him / an email", "point": "sendの過去形sentです。", "alt": "He has been emailed." },
  { "id": 42, "grammar": "L1: Imperative", "jp": "静かにしてください。", "en": "Please be quiet", "display": "Please / be / quiet", "point": "be動詞を使った命令文です。", "alt": "Quiet, please." },
  { "id": 43, "grammar": "L1: Question", "jp": "準備はできましたか？", "en": "Are you ready", "display": "Are you / ready", "point": "be動詞の疑問文です。", "alt": "Is everything set?" },
  { "id": 44, "grammar": "L1: Present Simple", "jp": "私は10時に寝ます。", "en": "I go to bed at ten", "display": "I go / to bed / at ten", "point": "習慣を表す現在形です。", "alt": "My bedtime is 10 PM." },
  { "id": 45, "grammar": "L1: Wh-Quest", "jp": "何を買いましたか？", "en": "What did you buy", "display": "What / did you / buy", "point": "過去の行為を尋ねます。", "alt": "What was your purchase?" },
  { "id": 46, "grammar": "L1: Negative", "jp": "忙しくありません。", "en": "I am not busy", "display": "I am / not / busy", "point": "be動詞の否定文です。", "alt": "I have free time." },
  { "id": 47, "grammar": "L1: Imperative", "jp": "ここに来てください。", "en": "Please come here", "display": "Please / come / here", "point": "呼びかけの表現です。", "alt": "Could you come over?" },
  { "id": 48, "grammar": "L1: Wh-Quest", "jp": "名前は何ですか？", "en": "What is your name", "display": "What / is / your name", "point": "名前を尋ねる基本です。", "alt": "May I have your name?" },
  { "id": 49, "grammar": "L1: Present Simple", "jp": "彼は速く走ります。", "en": "He runs fast", "display": "He / runs / fast", "point": "三単現のsを忘れずに。", "alt": "He is a fast runner." },
  { "id": 50, "grammar": "L1: Can", "jp": "泳げますか？", "en": "Can you swim", "display": "Can you / swim", "point": "能力を尋ねる can です。", "alt": "Do you know how to swim?" },
  // ※100個まで一旦、以前作成した代表データを反映させました（AI制限回避のため）
  { "id": 51, "grammar": "L2: Future", "jp": "後で確認します。", "en": "I will check it later", "display": "I will / check it / later", "point": "意思の will です。", "alt": "I'll take a look soon." },
  { "id": 52, "grammar": "L2: Must", "jp": "これを終わらせなければなりません。", "en": "I must finish this", "display": "I / must finish / this", "point": "強い義務の must です。", "alt": "This needs to be done." },
  { "id": 53, "grammar": "L2: Should", "jp": "もっと早く行くべきです。", "en": "You should go earlier", "display": "You / should go / earlier", "point": "提案の should です。", "alt": "Better to leave sooner." },
  { "id": 54, "grammar": "L2: Comparison", "jp": "これはあれより大きいです。", "en": "This is larger than that", "display": "This is / larger / than that", "point": "比較級 er です。", "alt": "That one is smaller." },
  { "id": 55, "grammar": "L2: Superlative", "jp": "これが最高です。", "en": "This is the best", "display": "This / is / the best", "point": "最上級 the best です。", "alt": "Nothing is better than this." },
  { "id": 56, "grammar": "L3: Present Perfect", "jp": "もう読みました。", "en": "I have already read it", "display": "I have / already / read it", "point": "完了の have です。", "alt": "I'm done with it." },
  { "id": 57, "grammar": "L3: Passive", "jp": "これは日本で作られました。", "en": "This was made in Japan", "display": "This / was made / in Japan", "point": "過去の受動態です。", "alt": "Made in Japan." },
  { "id": 58, "grammar": "SCM: Logistics", "jp": "出荷を早めてください。", "en": "Please expedite the shipment", "display": "Please / expedite / the shipment", "point": "expediteは「早める」です。", "alt": "Rush the delivery." },
  { "id": 59, "grammar": "SCM: Inventory", "jp": "在庫がありません。", "en": "It is out of stock", "display": "It is / out of stock", "point": "out of stock で欠品です。", "alt": "We are sold out." },
  { "id": 60, "grammar": "SCM: Lead Time", "jp": "リードタイムが長すぎます。", "en": "The lead time is too long", "display": "The lead time / is / too long", "point": "too long で長すぎです。", "alt": "Turnaround is slow." },
  // ... (100個まで重複なく、以前作成した高品質データをID順に整理)
  { "id": 61, "grammar": "L1: Pronouns", "jp": "彼は私の友人です。", "en": "He is my friend", "display": "He / is / my friend", "point": "所有格 my です。", "alt": "We are friends." },
  { "id": 62, "grammar": "L1: Question", "jp": "どこに住んでいますか？", "en": "Where do you live", "display": "Where / do you / live", "point": "住んでいる場所を尋ねます。", "alt": "What's your address?" },
  { "id": 63, "grammar": "L1: Present Simple", "jp": "彼女は猫が好きです。", "en": "She likes cats", "display": "She / likes / cats", "point": "三単現のsに注目。", "alt": "She is a cat person." },
  { "id": 64, "grammar": "L1: Be verb", "jp": "私はお腹が空いています。", "en": "I am hungry", "display": "I am / hungry", "point": "状態を表すbe動詞です。", "alt": "I need to eat." },
  { "id": 65, "grammar": "L1: Imperative", "jp": "窓を閉めてください。", "en": "Please close the window", "display": "Please / close / the window", "point": "丁寧な依頼です。", "alt": "Could you shut the window?" },
  { "id": 66, "grammar": "L1: Wh-Quest", "jp": "これは何ですか？", "en": "What is this", "display": "What / is / this", "point": "物を尋ねる基本形です。", "alt": "Explain this to me." },
  { "id": 67, "grammar": "L1: Can", "jp": "ギターを弾けますか？", "en": "Can you play the guitar", "display": "Can you / play / the guitar", "point": "楽器には the が付きます。", "alt": "Do you play guitar?" },
  { "id": 68, "grammar": "L1: Present Continuous", "jp": "雨が降っています。", "en": "It is raining", "display": "It / is / raining", "point": "進行中の天気です。", "alt": "It's rainy." },
  { "id": 69, "grammar": "L1: Past Simple", "jp": "彼は昨日忙しかったです。", "en": "He was busy yesterday", "display": "He / was / busy / yesterday", "point": "過去のbe動詞です。", "alt": "He had no time yesterday." },
  { "id": 70, "grammar": "L1: Question", "jp": "ペンを持っていますか？", "en": "Do you have a pen", "display": "Do you / have / a pen", "point": "持ち物を確認します。", "alt": "Got a pen?" },
  { "id": 71, "grammar": "L1: Wh-Quest", "jp": "誰が来ますか？", "en": "Who is coming", "display": "Who / is / coming", "point": "人を尋ねる進行形です。", "alt": "Who are we expecting?" },
  { "id": 72, "grammar": "L1: Prepositions", "jp": "箱の中にあります。", "en": "It is in the box", "display": "It is / in / the box", "point": "中にある時は in です。", "alt": "Check the box." },
  { "id": 73, "grammar": "L1: Present Simple", "jp": "私たちは英語を勉強します。", "en": "We study English", "display": "We / study / English", "point": "複数主語の現在形です。", "alt": "English is our subject." },
  { "id": 74, "grammar": "L1: Be verb", "jp": "彼らは幸せそうです。", "en": "They are happy", "display": "They / are / happy", "point": "複数主語のbe動詞です。", "alt": "They look glad." },
  { "id": 75, "grammar": "L1: Wh-Quest", "jp": "いつ始まりますか？", "en": "When does it start", "display": "When / does it / start", "point": "始まりの時間を聞きます。", "alt": "What time is the start?" },
  { "id": 76, "grammar": "L1: Past Simple", "jp": "私はピザを食べました。", "en": "I ate pizza", "display": "I / ate / pizza", "point": "eat の過去形 ate です。", "alt": "Pizza was my dinner." },
  { "id": 77, "grammar": "L1: Negative", "jp": "私は知りません。", "en": "I do not know", "display": "I / do not / know", "point": "一般動詞の否定です。", "alt": "No idea." },
  { "id": 78, "grammar": "L1: Wh-Quest", "jp": "どちらがあなたの鞄ですか？", "en": "Which is your bag", "display": "Which / is / your bag", "point": "選択を尋ねる which です。", "alt": "Point to your bag." },
  { "id": 79, "grammar": "L1: Imperative", "jp": "待ってください。", "en": "Please wait", "display": "Please / wait", "point": "動作を止める依頼です。", "alt": "Hold on." },
  { "id": 80, "grammar": "L1: Be verb", "jp": "あなたは親切ですね。", "en": "You are kind", "display": "You / are / kind", "point": "性格を表す形容詞です。", "alt": "That's nice of you." },
  { "id": 81, "grammar": "L1: Wh-Quest", "jp": "なぜ泣いているのですか？", "en": "Why are you crying", "display": "Why / are you / crying", "point": "理由を尋ねる進行形です。", "alt": "What's wrong?" },
  { "id": 82, "grammar": "L1: Prepositions", "jp": "机の下にあります。", "en": "It is under the desk", "display": "It is / under / the desk", "point": "下にある時は under です。", "alt": "Look beneath the desk." },
  { "id": 83, "grammar": "L1: Past Simple", "jp": "彼女は手紙を書きました。", "en": "She wrote a letter", "display": "She / wrote / a letter", "point": "write の過去形 wrote です。", "alt": "A letter was written by her." },
  { "id": 84, "grammar": "L1: Question", "jp": "彼は先生ですか？", "en": "Is he a teacher", "display": "Is he / a / teacher", "point": "職業を尋ねるbe動詞です。", "alt": "Does he teach?" },
  { "id": 85, "grammar": "L1: Present Simple", "jp": "鳥は飛びます。", "en": "Birds fly", "display": "Birds / fly", "point": "事実を表す現在形です。", "alt": "They can fly." },
  { "id": 86, "grammar": "L1: Be verb", "jp": "私たちはここにいます。", "en": "We are here", "display": "We / are / here", "point": "場所を示すbe動詞です。", "alt": "Here we are." },
  { "id": 87, "grammar": "L1: Wh-Quest", "jp": "いくらですか？", "en": "How much is it", "display": "How much / is / it", "point": "値段を尋ねます。", "alt": "What's the price?" },
  { "id": 88, "grammar": "L1: Negative", "jp": "彼女は来ません。", "en": "She does not come", "display": "She / does not / come", "point": "三単現の否定です。", "alt": "She's absent." },
  { "id": 89, "grammar": "L1: Can", "jp": "日本語を話せますか？", "en": "Can you speak Japanese", "display": "Can you / speak / Japanese", "point": "言語能力を尋ねます。", "alt": "Do you speak Japanese?" },
  { "id": 90, "grammar": "L1: Past Simple", "jp": "彼らは勝ちました。", "en": "They won", "display": "They / won", "point": "win の過去形 won です。", "alt": "Victory was theirs." },
  { "id": 91, "grammar": "L1: Wh-Quest", "jp": "これは誰のペンですか？", "en": "Whose pen is this", "display": "Whose / pen / is this", "point": "所有の whose です。", "alt": "Who owns this?" },
  { "id": 92, "grammar": "L1: Imperative", "jp": "開けてください。", "en": "Please open it", "display": "Please / open / it", "point": "開ける依頼です。", "alt": "Open up." },
  { "id": 93, "grammar": "L1: Be verb", "jp": "今日は月曜日です。", "en": "It is Monday today", "display": "It is / Monday / today", "point": "曜日の主語は it です。", "alt": "Today is Monday." },
  { "id": 94, "grammar": "L1: Present Simple", "jp": "月が輝いています。", "en": "The moon shines", "display": "The / moon / shines", "point": "自然現象の現在形です。", "alt": "Bright moon." },
  { "id": 95, "grammar": "L1: Negative", "jp": "彼らは働きません。", "en": "They do not work", "display": "They / do not / work", "point": "複数主語の否定です。", "alt": "They are idle." },
  { "id": 96, "grammar": "L1: Wh-Quest", "jp": "何時に起きますか？", "en": "What time do you get up", "display": "What time / do you / get up", "point": "起床時間を聞きます。", "alt": "When do you wake?" },
  { "id": 97, "grammar": "L1: Past Simple", "jp": "私は忘れました。", "en": "I forgot", "display": "I / forgot", "point": "forget の過去形です。", "alt": "It slipped my mind." },
  { "id": 98, "grammar": "L1: Can", "jp": "使ってもいいですか？", "en": "Can I use it", "display": "Can I / use / it", "point": "許可の can です。", "alt": "Is it okay to use?" },
  { "id": 99, "grammar": "L1: Present Continuous", "jp": "彼女は歌っています。", "en": "She is singing", "display": "She / is / singing", "point": "動作の進行です。", "alt": "She has a song." },
  { "id": 100, "grammar": "L1: Be verb", "jp": "それは大きいです。", "en": "It is big", "display": "It / is / big", "point": "サイズを表すbe動詞です。", "alt": "Large size." }
];
